[book]
title = "Alter Ego Docs"
description = "Documentation for the Alter Ego Project"
src = "Docs"

[build]
create-missing = false

[preprocessor]

[output]

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/MolSnoo/Alter-Ego"
edit-url-template = "https://github.com/MolSnoo/Alter-Ego/edit/master/{path}"
site-url = "https://molsnoo.github.io/Alter-Ego"
